# Generated by Django 3.2.6 on 2021-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodePositions',
            fields=[
                ('sid', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
