# Generated by Django 3.2.6 on 2021-10-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodepositions',
            name='type',
            field=models.CharField(default='say-item', max_length=16),
        ),
    ]
